version: '3.8'

services:
  # Nginx + PHP Application
  app:
    build: .
    container_name: crud-user-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/sites-available/default
    depends_on:
      db:
        condition: service_healthy
    networks:
      - crud-network
    environment:
      - PHP_OPCACHE_ENABLE=1
      - PHP_OPCACHE_REVALIDATE_FREQ=0
      - DB_HOST=db
      - DB_NAME=crud_user
      - DB_USER=root
      - DB_PASS=rootpassword

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: crud-user-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: crud_user
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: cruduser
      MYSQL_PASSWORD: crudpass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "3307:3306"
    networks:
      - crud-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: crud-user-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - crud-network

volumes:
  mysql_data:

networks:
  crud-network:
    driver: bridge
