version: '3.8'

services:
  # Web Server (Nginx)
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - app-network
    restart: unless-stopped

  # PHP-FPM
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    volumes:
      - ./src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network
    depends_on:
      - mysql
    restart: unless-stopped

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_DATABASE: app_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password_123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - app-network
    restart: unless-stopped

  
    # FrankenPHP Server
  frankenphp:
    image: dunglas/frankenphp:php8.3
    container_name: frankenphp_server
    ports:
      - "8090:80"
      - "8443:443"
    command:
      - |
        install-php-extensions \
        pdo_mysql \
        gd \
        intl \
        zip \
      opcache
    volumes:
      - ./src:/app/public
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile
      - ./frankenphp/php.ini:/usr/local/etc/php/php.ini
    environment:
      - SERVER_NAME=:80
    networks:
      - app-network
    depends_on:
      - mysql
    restart: unless-stopped

  # phpMyAdmin (Optional - untuk management database)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: app_user
      PMA_PASSWORD: app_password_123
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge